config/routes.rb
Rails.application.routes.draw do
  resources :books


  root to:'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
   validates :title, presence: true
   validates :body, presence: true
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to "/books/#{@book.id}"
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Edding Book</h1>
<!-- form_with部分 -->
<%= form_with model:@book, local: true do |f| %>
 <% @book.errors.full_messages.each do |message| %>
 <div class="form-error">
  <%= @book.errors.count %>error prohibited this book from being saved
  <%= message %>
 </div>
 <% end %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show",book_path %>
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
 <thead>
  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3"></th>
  </tr>
 </thead>
 <tbody>
  <% @books.each do |book| %>
   <tr class = "table">
    <td class = "book-title"><%= book.title %></td>
    <td class = "book-body"><%= book.body %></td>
    <td class = "show"><%= link_to "Show", book_path(book) %></td>
    <td class = "edit"><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td class = "destroy"><%= link_to "Destroy", book_path(book), method: :delete %></td>
   </tr>
  <% end %>
 </tbody>
</table>


<%= form_for(@book) do |f| %>
<h2>New book</h2>
<% @book.errors.full_messages.each do |message| %>
 <div class="form-error">
  <%= @book.errors.count %> error prohibited this book from being saved
  <%= message %>
 </div>
<% end %>
<h4>Title</h4>
 <%= f.text_field :title %>
 <h4>Body</h4>
 <%= f.text_field :body %>
 <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
<% end %>


<h3 class ="book-title">Title:<%= @book.title %></h3>
<h3 class = "book-body">Body:<%= @book.body %></h3>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>
  "ようこそ"
  <strong>Bookers</strong>
  "へ"
</h1>
<p>
  <strong>
    Bookers
  </strong>
  "では、さまざまな書籍に関するあなたの意見や"
</p>
<p>印象を共有し交換することができます</p>
<span><%= link_to "Start", "/books" %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>